language: python

python:
  - 2.6
  - 2.7

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install python-gtk2 gawk

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .

script:
  - cd slugathon
  - py.test --cov slugathon --cov-report term-missing test/

after_success:
  - coveralls
  - pyflakes . | awk -F: '{printf "%s:%s: [E]%s\n", $1, $2, $3}'
  - pep8 -r .

notifications:
  email: false
